### ISSUE TITLE
Bug: Chat messages are not being sent to other user, getting exception

### ISSUE THREAD

**Issue by cchunduri** [Tonterias/spingularchatsql6#22]
**Reproducible Steps:**

1. Log in with your user name and password
2. Type system in the search user field
3. Select system user
4. In the messages box, type message and click send button
5. Messages will not be sent and open network tab in browser devtools, you can observe below error
![image](https://user-images.githubusercontent.com/3481121/65348454-d8622e80-dbfe-11e9-95f6-c7f0182a4b25.png)

**Stacktrace at Backend:**

org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["FK_CHAT_MESSAGE_CHAT_USER_ID: PUBLIC.CHAT_MESSAGE FOREIGN KEY(CHAT_USER_ID) REFERENCES PUBLIC.CHAT_USER(ID) (1152)"; SQL statement:
insert into chat_message (chat_room_id, chat_user_id, is_delivered, is_received, message, message_sent_at, id) values (?, ?, ?, ?, ?, ?, ?) [23506-199]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:296)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:253)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:536)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:746)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:714)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:534)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:305)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.spingular.chat.service.impl.ChatMessageServiceImpl$$EnhancerBySpringCGLIB$$c149e789.save(<generated>)
	at com.spingular.chat.web.websocket.ChatService.sendChat(ChatService.java:68)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:550)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:503)
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:93)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:505)
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:439)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3176)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3690)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:90)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:478)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:356)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1454)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:511)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3290)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2486)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:473)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:178)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:39)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:271)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:104)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:532)
	... 26 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "FK_CHAT_MESSAGE_CHAT_USER_ID: PUBLIC.CHAT_MESSAGE FOREIGN KEY(CHAT_USER_ID) REFERENCES PUBLIC.CHAT_USER(ID) (1152)"; SQL statement:
insert into chat_message (chat_room_id, chat_user_id, is_delivered, is_received, message, message_sent_at, id) values (?, ?, ?, ?, ?, ?, ?) [23506-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:457)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:319)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:261)
	at org.h2.table.Table.fireConstraints(Table.java:1020)
	at org.h2.table.Table.fireAfterRow(Table.java:1038)
	at org.h2.command.dml.Insert.insertRows(Insert.java:194)
	at org.h2.command.dml.Insert.update(Insert.java:132)
	at org.h2.command.CommandContainer.update(CommandContainer.java:133)
	at org.h2.command.Command.executeUpdate(Command.java:267)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:200)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:154)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 43 common frames omitted

2019-09-20 23:19:37.387  WARN 1673 --- [ XNIO-2 task-22] o.z.problem.spring.common.AdviceTraits   : Bad Request: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'chatMessageCriteria' on field 'chatRoomId.equals': rejected value [undefined]; codes [typeMismatch.chatMessageCriteria.chatRoomId.equals,typeMismatch.chatRoomId.equals,typeMismatch.equals,typeMismatch.java.lang.Long,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [chatMessageCriteria.chatRoomId.equals,chatRoomId.equals]; arguments []; default message [chatRoomId.equals]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Long' for property 'chatRoomId.equals'; nested exception is java.lang.NumberFormatException: For input string: "undefined"]
2019-09-20 23:19:37.389  WARN 1673 --- [ XNIO-2 task-22] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'chatMessageCriteria' on field 'chatRoomId.equals': rejected value [undefined]; codes [typeMismatch.chatMessageCriteria.chatRoomId.equals,typeMismatch.chatRoomId.equals,typeMismatch.equals,typeMismatch.java.lang.Long,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [chatMessageCriteria.chatRoomId.equals,chatRoomId.equals]; arguments []; default message [chatRoomId.equals]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Long' for property 'chatRoomId.equals'; nested exception is java.lang.NumberFormatException: For input string: "undefined"]]

**Comment by Tonterias** [comment]
Good point Chaitanya, but I think we will fix this issue once #15 is included. Don't you think so?

Please, when you think that the answer closes the issue, the one who opened the issue should close it. When you do not agree, the conversation should continue. In Jhipster GitHub if you do not close it in a few day, one of the moderators close them. We should think about the best way to do it here. Thanks.

**Comment by cchunduri** [comment]
This issue will be addressed in Issue #15, closing this issue.
